---
title: OSPAR Hazardous substances Assessment Tool
output:
  github_document:
    html_preview: false
params:
  compartment: "biota"
  series: "Belgium BCP HCHA Crangon crangon"
---

```{r setup, echo=FALSE}
# stops jittering from looking like a new plot
set.seed(20342309)
# load 2019 data
load("2019/assessment_platform.RData")
```

As an example this markdown document has been produced using the
code in the 2019 folder. In practice, an HTML document is produced,
which can be accessed at the link below:

https://ocean.ices.dk/OHAT/Home/GettrResult?seriesID=Belgium%20BCP%20HCHA%20Crangon%20crangon&matrix=Biota&year=2019

The graphical map interface to all assessments can be found here:
https://ocean.ices.dk/ohat/
or
http://ices.dk/data/assessment-tools/Pages/ospar-cat-app.aspx

```{r child = "2019/assessment platform.Rmd"}
```

### how to build this file

this file was created using (requires access to `assessment_platform.RData`)

```{r eval = FALSE}
rmarkdown::render("README.Rmd")
```